services:
  django:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - POSTGES_NAME=postgres-db
      - POSTGES_USER=postgres
      - POSTGES_PASSWORD=
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres-db
      - POSTGES_USER=postgres
      - POSTGES_PASSWORD=postgres
      
